### ISSUE TITLE
asc2eph fails when compiling DE441

### ISSUE THREAD

**Issue by toddcarnes** [Bill-Gray/jpl_eph#8]
DE441 ends up 11000 years short when you try to make a binary ephemeris file from the files downloaded at ftp://ssd.jpl.nasa.gov/pub/eph/planets/ascii/de441.

Instead of an ephemeris that runs from -13000 to 17000, it cuts off and you only get a partial file running from -13000 to 5999.

The same files have successfully been used to create the full binary DE441 using the fortran program asc2eph.f located at ftp://ssd.jpl.nasa.gov/pub/eph/planets/fortran/.

**Comment by Bill-Gray** [comment]
Hmmm... no idea on this one,  but I hadn't downloaded the full ephemeris yet (my Internet connection is not all that fast).  I'd just got files for a few millennia near the present.  Downloading files as I write to test it out here.
Are you getting any error message(s)?  Does the resulting file run properly through `testeph` (except,  presumably,  for warning you that the file doesn't cover the entire range that it ought to)?

**Comment by toddcarnes** [comment]
No. It runs, makes the ephemeris and exits normally. I don't get any errors or anything.

The only reason I caught it was because I noticed it was over a gig smaller than DE431 even though they cover the same time range.

I ran dump_eph on it and it reported that the file ended at 5999 instead of 17000.

The guys over on the Swiss Ephemeris list downloaded the same files and used NASA's fortran program to compile them and ended up with the whole thing from -13000 to 17000 and it was exactly the same size as DE431 down to the byte.

FWIW, I used asc2eph for DE440 just prior to DE441 and everything was fine.

I kinda wondered if it had something to do with the way JPL chose to break the files up into smaller pieces this time.

**Comment by toddcarnes** [comment]
I even tried deleting all the files, re-downloading them and re-compiling (3 times) just in case the files were getting corrupted or something, but it didn't make a difference.

**Comment by Bill-Gray** [comment]
Yup,  it's not just you.  With just the `ascp05000.441` and `ascp06000.441`,  I get the same thing;  it processes the first file and stops at the year 6000.  Investigating...

**Comment by Bill-Gray** [comment]
Found problem and am fixing it.  See line 166 of `asc2eph.cpp`,  where it's assumed that only DE-431 goes past the year 6000.  True at the time,  but now DE-441 does the same thing.

I've made a simple change that removes any need to make assumptions about a maximum date.  Just need to make sure it works before I add/commit/push the change.

Thanks for the bug report!

**Comment by Bill-Gray** [comment]
...And the fix works.  (With the added benefit of the code not making foolish assumptions anymore about just how far into the future a given ephemeris goes.  I've talked with folks interested in making ephems in this format spanning hundreds of millennia,  but with lower precision;  there are no particular guarantees about DE time spans.)

**Comment by toddcarnes** [comment]
You're quick. :)
